name: Frontend Auto Deploy to S3

on:
  push:
    branches:
      - feat/deploy/#80

jobs:
  Deploy_Frontend_to_EC2:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 서버에 SSH 원격 접속 후 프론트엔드 배포 작업 수행
        uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            # 작업 디렉토리로 이동
            cd /home/ubuntu/local-community-web/frontend

            # 원격 브랜치를 강제로 가져오기 및 체크아웃
            git fetch origin feat/deploy/#80:feat/deploy/#80 || echo "Branch fetch failed"
            git checkout feat/deploy/#80 || git checkout -b feat/deploy/#80 origin/feat/deploy/#80

            # 최신 원격 브랜치와 강제 동기화
            git reset --hard origin/feat/deploy/#80 || echo "Reset failed"

            # 의존성 설치
            npm install || echo "npm install failed"

            # 프로젝트 빌드
            npm run build || echo "npm run build failed"

            # S3로 빌드 결과물 동기화
            aws s3 sync build/ s3://town-in-web-page --region ap-northeast-2 --delete || echo "S3 sync failed"

            # 배포 확인 메시지 출력
            echo "Frontend has been deployed from feat/deploy/#80 branch."
